[package]
name = "asc-policy-engine"
description = "Product Policy template compiler for AgentSecCore V2"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
tracing.workspace = true
asc-pap = { workspace = true }
asc-policy-types = { workspace = true }

[dev-dependencies]
asc-foundation-types = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
