//! Versioned, SDK-independent propagation envelope and raw-byte budgets.
use serde::de::Error as _;
use serde::{Deserialize, Deserializer, Serialize};
use std::collections::BTreeMap;

/// Existing business request/response capacity, including the terminating LF.
pub const BUSINESS_FRAME_BYTES: usize = 4 * 1024 * 1024;
/// Additional request-only capacity for propagation members.
pub const CONTEXT_FRAME_BYTES: usize = 32 * 1024;
/// Transport admission bound; responses keep the original bound.
pub const MAX_REQUEST_FRAME_BYTES: usize = BUSINESS_FRAME_BYTES + CONTEXT_FRAME_BYTES;

/// W3C propagation strings. Schema failures reject the request; malformed W3C
/// contents are handled by the tracing adapter without rejecting business work.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct TraceCarrierV1 {
    /// Required wire version (currently 1).
    #[serde(deserialize_with = "version_one")]
    pub version: u8,
    /// W3C parent; explicit null is invalid.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_string"
    )]
    pub traceparent: Option<String>,
    /// W3C trace state; explicit null is invalid.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_string"
    )]
    pub tracestate: Option<String>,
    /// Bounded, allowlisted Agent attribution.
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present_string"
    )]
    pub baggage: Option<String>,
}

impl TraceCarrierV1 {
    /// Header map suitable for an `OTel` extractor without an SDK dependency here.
    pub fn headers(&self) -> std::collections::HashMap<String, String> {
        [
            ("traceparent", &self.traceparent),
            ("tracestate", &self.tracestate),
            ("baggage", &self.baggage),
        ]
        .into_iter()
        .filter_map(|(key, value)| value.as_ref().map(|value| (key.to_owned(), value.clone())))
        .collect()
    }

    /// Constructs a wire carrier from an `OTel` injector's output.
    pub fn from_headers(mut headers: std::collections::HashMap<String, String>) -> Self {
        Self {
            version: 1,
            traceparent: headers.remove("traceparent"),
            tracestate: headers.remove("tracestate"),
            baggage: headers.remove("baggage"),
        }
    }
}

/// Boundary-only labels retained for V1 callers. They do not set `OTel` IDs.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CompatibilityV1 {
    /// Required wire version (currently 1).
    #[serde(deserialize_with = "version_one")]
    pub version: u8,
    /// Opaque caller-supplied V1 trace label.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
    /// Explicit caller invocation label; never generated by V2.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub invocation_label: Option<String>,
}

fn version_one<'de, D: Deserializer<'de>>(de: D) -> Result<u8, D::Error> {
    let version = u8::deserialize(de)?;
    if version == 1 {
        Ok(version)
    } else {
        Err(D::Error::custom("unsupported context version"))
    }
}
fn present_string<'de, D: Deserializer<'de>>(de: D) -> Result<Option<String>, D::Error> {
    String::deserialize(de).map(Some)
}

/// Checks independent budgets after strict envelope decoding. Counts original
/// bytes (including whitespace and escape spellings), never reserializes params.
/// A member's key/colon/adjacent whitespace and comma count toward its budget.
/// The braces and LF are charged to the business envelope.
///
/// # Errors
/// Returns malformed JSON errors. Callers must also decode `DaemonRequest` to
/// reject duplicate members and enforce the schema before dispatching.
pub fn request_fits_budget(bytes: &[u8]) -> Result<bool, serde_json::Error> {
    let _: BTreeMap<String, &serde_json::value::RawValue> = serde_json::from_slice(bytes)?;
    let mut depth = 0_usize;
    let mut quoted = false;
    let mut escaped = false;
    let mut start = 0;
    let mut context = 0;
    let mut members = 0_usize;
    let mut context_members = 0;
    for (index, &byte) in bytes.iter().enumerate() {
        if quoted {
            if escaped {
                escaped = false;
            } else if byte == b'\\' {
                escaped = true;
            } else if byte == b'"' {
                quoted = false;
            }
            continue;
        }
        match byte {
            b'"' => quoted = true,
            b'{' | b'[' => {
                depth += 1;
                if depth == 1 {
                    start = index + 1;
                }
            }
            b'}' | b']' => {
                if depth == 1 {
                    let size = context_member_bytes(&bytes[start..index]);
                    context += size;
                    context_members += usize::from(size > 0);
                    members += 1;
                }
                depth -= 1;
            }
            b',' if depth == 1 => {
                let size = context_member_bytes(&bytes[start..index]);
                context += size;
                context_members += usize::from(size > 0);
                members += 1;
                start = index + 1;
            }
            _ => {}
        }
    }
    context += context_members.min(members.saturating_sub(1));
    // Service dispatch strips LF. Reserve it even for EOF-terminated requests.
    let length = bytes.len() + usize::from(bytes.last() != Some(&b'\n'));
    Ok(context <= CONTEXT_FRAME_BYTES
        && length.saturating_sub(context) <= BUSINESS_FRAME_BYTES
        && length <= MAX_REQUEST_FRAME_BYTES)
}
fn context_member_bytes(member: &[u8]) -> usize {
    let mut decoder = serde_json::Deserializer::from_slice(member);
    if matches!(String::deserialize(&mut decoder), Ok(key) if key == "traceContext" || key == "compatibility")
    {
        member.len()
    } else {
        0
    }
}
