//! Production daemon admission and Runtime wiring.

use std::collections::BTreeMap;
use std::path::Component;

use cosh_gateway::daemon::{RuntimeFactory, ScheduledRun, StartedRuntime};
use cosh_gateway_contracts::error::{ContractError, ErrorCategory};

use super::*;
use crate::checkpoint::{CheckpointDriver, PreRuntimeCheckpointAdapter, TaskSnapshotAdapter};

struct RuntimeRouter {
    core: Option<Box<dyn RuntimeFactory>>,
    codex: Option<Box<dyn RuntimeFactory>>,
}

impl RuntimeRouter {
    fn new(core: Option<Box<dyn RuntimeFactory>>, codex: Option<Box<dyn RuntimeFactory>>) -> Self {
        Self { core, codex }
    }
}

impl RuntimeFactory for RuntimeRouter {
    fn open(&mut self, run: &ScheduledRun) -> Result<StartedRuntime, ContractError> {
        let factory = match runtime_route(&run.runtime)? {
            RuntimeRoute::Core => &mut self.core,
            RuntimeRoute::Codex => &mut self.codex,
        };
        factory.as_mut().ok_or_else(runtime_unavailable)?.open(run)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum RuntimeRoute {
    Core,
    Codex,
}

fn runtime_route(selector: &RuntimeSelector) -> Result<RuntimeRoute, ContractError> {
    match (
        selector.runtime.as_str(),
        selector.profile.as_ref().map(BoundedName::as_str),
    ) {
        ("core", Some(GATEWAY_BROKERED_CORE_RUNTIME_PROFILE))
        | ("core", Some(GATEWAY_CHECKPOINT_CORE_RUNTIME_PROFILE))
        | ("core", Some(GATEWAY_WORKSPACE_WRITE_CORE_RUNTIME_PROFILE)) => Ok(RuntimeRoute::Core),
        ("acp", Some("codex")) => Ok(RuntimeRoute::Codex),
        _ => Err(runtime_unavailable()),
    }
}

fn runtime_unavailable() -> ContractError {
    ContractError::new(
        "runtime_unavailable",
        ErrorCategory::RuntimeUnavailable,
        true,
        "The selected Task Runtime is not available in this Gateway",
    )
    .unwrap_or_else(|_| unreachable!("static Runtime routing error must remain bounded"))
}

#[derive(Debug, Clone, Args)]
pub(super) struct ServeArgs {
    /// Absolute Unix socket path; defaults below the user runtime directory.
    #[arg(long, value_name = "PATH")]
    pub(super) socket: Option<PathBuf>,
    /// Absolute private SQLite database path; defaults below user state.
    #[arg(long, value_name = "PATH")]
    pub(super) database: Option<PathBuf>,
    /// Absolute ws-ckpt socket enabling pre-Runtime baselines.
    #[arg(long, value_name = "PATH")]
    checkpoint_socket: Option<PathBuf>,
    /// Absolute append-only security audit log for governed effects.
    #[arg(long, value_name = "PATH")]
    security_audit: Option<PathBuf>,
    /// Provision this installation identity on first start; generated by default.
    #[arg(long, value_name = "INSTALLATION_ID")]
    pub(super) installation_id: Option<String>,
    /// Absolute installed cosh-core executable; omit to report Core unavailable.
    #[arg(long, value_name = "PATH")]
    core_executable: Option<PathBuf>,
    /// Absolute trusted Codex ACP adapter; omit to report Codex unavailable.
    #[arg(long, value_name = "PATH")]
    acp_adapter: Option<PathBuf>,
    /// Existing workspace directory admitted for every Task in this daemon.
    #[arg(long, default_value = ".")]
    pub(super) workspace: PathBuf,
    /// Live systemd service unit whose cgroup owns this production daemon.
    #[arg(long, value_name = "UNIT")]
    pub(super) systemd_unit: Option<String>,
    /// Presentation format for startup and stable errors.
    #[arg(long, value_enum, default_value_t = Output::Human)]
    pub(super) output: Output,
}

pub(super) fn serve(args: ServeArgs, reporter: &Reporter) -> Result<u8, CliError> {
    let installation_id = args
        .installation_id
        .map(InstallationId::parse)
        .transpose()
        .map_err(|error| CliError::Daemon(error.to_string()))?;
    if args.checkpoint_socket.is_none() && args.security_audit.is_some() {
        return Err(CliError::Profile(
            "--security-audit requires --checkpoint-socket".to_owned(),
        ));
    }
    if args.core_executable.is_none() && args.acp_adapter.is_none() {
        return Err(CliError::Profile(
            "serve requires at least one configured Runtime".to_owned(),
        ));
    }
    let configured_workspace = if args.workspace.is_absolute() {
        args.workspace.clone()
    } else {
        std::env::current_dir()
            .map_err(|error| CliError::Profile(error.to_string()))?
            .join(&args.workspace)
    };
    let configured_workspace = normalize_absolute_workspace(&configured_workspace)?;
    let workspaces = TrustedWorkspaceResolver::new_for_targets(
        [
            GatewayCapabilityProfile::task_only_v1().governed_target(),
            GatewayCapabilityProfile::workspace_checkpoint_v1().governed_target(),
            GatewayCapabilityProfile::workspace_write_v1().governed_target(),
            GatewayCapabilityProfile::delegated_acp_v1().governed_target(),
        ],
        &configured_workspace,
    )
    .map_err(|error| CliError::Profile(error.safe_message.as_str().to_owned()))?;
    let default_workspace = workspaces.workspace_ref().clone();
    if let Some(unit) = args.systemd_unit.as_deref() {
        LinuxSystemdContainmentVerifier::validate_unit(unit)
            .map_err(|error| CliError::Containment(error.to_string()))?;
    }
    let containment_unit = args.systemd_unit.as_deref().ok_or_else(|| {
        CliError::Containment("production serve requires --systemd-unit".to_owned())
    })?;
    let environment = std::env::vars_os().collect::<BTreeMap<_, _>>();
    let resolved_core_profile = args
        .core_executable
        .as_ref()
        .map(|path| {
            InstalledBrokeredCoreRuntimePortFactory::resolve(
                require_absolute(path, "brokered cosh-core executable")?,
                environment.clone(),
            )
            .map_err(|error| CliError::Profile(error.safe_message.as_str().to_owned()))
        })
        .transpose()?;
    let resolved_acp_profile = args
        .acp_adapter
        .as_ref()
        .map(|path| {
            AcpRuntimeProfileResolver::resolve(AcpRuntimeProfileRequest {
                profile: AcpRuntimeProfileId::Codex,
                executable: Some(require_absolute(path, "Codex ACP adapter executable")?),
                workspace: configured_workspace.clone(),
                environment: environment.clone(),
            })
            .map_err(|error| CliError::Profile(error.to_string()))
        })
        .transpose()?;
    let containment = LinuxSystemdContainmentVerifier::new()
        .verify(containment_unit)
        .map_err(|error| CliError::Containment(error.to_string()))?;
    let socket_path = daemon_socket_path(args.socket.as_ref())?;
    let database_path = daemon_database_path(args.database.as_ref())?;
    SqliteTaskStore::prepare_path(&database_path)
        .map_err(|error| CliError::Daemon(error.to_string()))?;
    let owner_uid = nix::unistd::Uid::effective().as_raw();
    let (
        mut checkpoint_driver,
        mut pre_runtime_checkpoint,
        mut task_snapshot_adapter,
        checkpoint_readiness,
    ) = if let Some(checkpoint_socket) = args.checkpoint_socket.as_ref() {
        let checkpoint_socket = require_absolute(checkpoint_socket, "ws-ckpt daemon socket")?;
        let audit_path = match args.security_audit {
            Some(path) => require_absolute(&path, "security audit")?,
            None => database_path.with_extension("security-audit.jsonl"),
        };
        if audit_conflicts_database(&audit_path, &database_path) {
            return Err(CliError::Profile(
                "security audit path must be distinct from Gateway database files".to_owned(),
            ));
        }
        match PreRuntimeCheckpointAdapter::admit(
            checkpoint_socket.clone(),
            &configured_workspace,
            default_workspace.clone(),
            owner_uid,
        ) {
            Ok(pre_runtime) => match CheckpointDriver::admit(
                GatewayCapabilityProfile::workspace_checkpoint_v1(),
                checkpoint_socket.clone(),
                &configured_workspace,
                audit_path,
                owner_uid,
            ) {
                Ok(brokered) => {
                    let snapshot = TaskSnapshotAdapter::admit(
                        checkpoint_socket.clone(),
                        &configured_workspace,
                        workspaces.clone(),
                        owner_uid,
                    )
                    .map_err(|error| CliError::Profile(error.to_string()))?;
                    (
                        Some(brokered),
                        Some(pre_runtime),
                        Some(snapshot),
                        configured_readiness(true, "")?,
                    )
                }
                Err(error) if error.is_unavailable() => (
                    None,
                    None,
                    None,
                    configured_readiness(false, "configured ws-ckpt is currently unavailable")?,
                ),
                Err(error) => return Err(CliError::Profile(error.to_string())),
            },
            Err(error) if error.is_unavailable() => (
                None,
                None,
                None,
                configured_readiness(false, "configured ws-ckpt is currently unavailable")?,
            ),
            Err(error) => return Err(CliError::Profile(error.to_string())),
        }
    } else {
        (
            None,
            None,
            None,
            configured_readiness(false, "ws-ckpt socket is not configured")?,
        )
    };
    let launch_catalog = TaskLaunchCatalog::new(
        default_workspace,
        configured_readiness(
            resolved_core_profile.is_some(),
            "Core executable is not configured",
        )?,
        configured_readiness(
            resolved_acp_profile.is_some(),
            "Codex ACP adapter is not configured",
        )?,
        checkpoint_readiness,
    );
    let config = GatewayDaemonConfig {
        socket_path,
        database_path,
        installation_id,
        launch_catalog,
    };
    let interrupted = install_interrupt_handler()?;
    let mut daemon =
        GatewayDaemon::bind(config).map_err(|error| CliError::Daemon(error.to_string()))?;
    let actor_resolver = LocalOsActorResolver::new(daemon.installation_id().clone(), owner_uid);
    let worker_id = BoundedOpaque::new(RuntimeInstanceId::new().to_string())
        .map_err(|error| CliError::Daemon(error.to_string()))?;
    let core_factory = resolved_core_profile
        .map(|profile| {
            InstalledBrokeredCoreRuntimePortFactory::from_resolved(
                daemon.installation_id().clone(),
                actor_resolver.clone(),
                workspaces.clone(),
                profile,
            )
            .map(|factory| {
                Box::new(ScheduledAgentRuntimeFactory::new(factory)) as Box<dyn RuntimeFactory>
            })
            .map_err(|error| CliError::Profile(error.safe_message.as_str().to_owned()))
        })
        .transpose()?;
    let codex_factory = resolved_acp_profile
        .map(|resolved_profile| {
            let mut profiles = BTreeMap::new();
            profiles.insert(AcpRuntimeProfileId::Codex, resolved_profile);
            InstalledAcpRuntimePortFactory::from_resolved_profiles(
                daemon.installation_id().clone(),
                actor_resolver.clone(),
                workspaces,
                profiles,
            )
            .map(|factory| {
                Box::new(ScheduledAgentRuntimeFactory::new(factory)) as Box<dyn RuntimeFactory>
            })
            .map_err(|error| CliError::Profile(error.safe_message.as_str().to_owned()))
        })
        .transpose()?;
    let router = Box::new(RuntimeRouter::new(core_factory, codex_factory));
    if let Some(driver) = checkpoint_driver.take() {
        daemon
            .attach_brokered_scheduler(containment, worker_id, router, Box::new(driver))
            .map_err(|error| CliError::Daemon(error.to_string()))?;
    } else {
        daemon
            .attach_task_only_scheduler(containment, worker_id, router)
            .map_err(|error| CliError::Daemon(error.to_string()))?;
    }
    if let Some(driver) = pre_runtime_checkpoint.take() {
        daemon
            .attach_pre_runtime_checkpoint_driver(Box::new(driver))
            .map_err(|error| CliError::Daemon(error.to_string()))?;
    }
    if let Some(driver) = task_snapshot_adapter.take() {
        daemon
            .attach_task_snapshot_driver(Box::new(driver))
            .map_err(|error| CliError::Daemon(error.to_string()))?;
    }
    reporter.event("daemon_ready", json!({}))?;
    daemon
        .serve_until(interrupted.as_ref())
        .map_err(|error| CliError::Daemon(error.to_string()))?;
    Ok(0)
}

pub(super) fn normalize_absolute_workspace(path: &Path) -> Result<PathBuf, CliError> {
    if !path.is_absolute() {
        return Err(CliError::Profile(
            "workspace path must resolve to an absolute path".to_owned(),
        ));
    }
    let mut normalized = PathBuf::from("/");
    for component in path.components() {
        match component {
            Component::RootDir | Component::CurDir => {}
            Component::Normal(part) => normalized.push(part),
            Component::ParentDir => {
                if !normalized.pop() {
                    return Err(CliError::Profile(
                        "workspace path must not traverse above root".to_owned(),
                    ));
                }
            }
            Component::Prefix(_) => {
                return Err(CliError::Profile(
                    "workspace path uses an unsupported platform prefix".to_owned(),
                ));
            }
        }
    }
    Ok(normalized)
}

fn audit_conflicts_database(audit_path: &Path, database_path: &Path) -> bool {
    if audit_path == database_path {
        return true;
    }
    ["-wal", "-shm"]
        .into_iter()
        .map(|suffix| {
            let mut companion = database_path.as_os_str().to_os_string();
            companion.push(suffix);
            PathBuf::from(companion)
        })
        .any(|companion| audit_path == companion)
}

fn configured_readiness(ready: bool, reason: &str) -> Result<LaunchReadiness, CliError> {
    if ready {
        Ok(LaunchReadiness::Ready)
    } else {
        Ok(LaunchReadiness::Unavailable {
            reason: BoundedText::new(reason)
                .map_err(|error| CliError::Profile(error.to_string()))?,
        })
    }
}

#[cfg(test)]
mod runtime_router_tests {
    use super::*;

    fn selector(runtime: &str, profile: &str) -> RuntimeSelector {
        RuntimeSelector {
            runtime: BoundedName::new(runtime).unwrap(),
            profile: Some(BoundedName::new(profile).unwrap()),
        }
    }

    #[test]
    fn routes_only_sealed_core_and_codex_selectors() {
        assert_eq!(
            runtime_route(&selector("core", GATEWAY_BROKERED_CORE_RUNTIME_PROFILE)).unwrap(),
            RuntimeRoute::Core
        );
        assert_eq!(
            runtime_route(&selector("acp", "codex")).unwrap(),
            RuntimeRoute::Codex
        );

        assert_eq!(
            runtime_route(&selector("core", GATEWAY_CHECKPOINT_CORE_RUNTIME_PROFILE)).unwrap(),
            RuntimeRoute::Core
        );
        assert_eq!(
            runtime_route(&selector(
                "core",
                GATEWAY_WORKSPACE_WRITE_CORE_RUNTIME_PROFILE
            ))
            .unwrap(),
            RuntimeRoute::Core
        );

        for rejected in [selector("acp", "claude-code"), selector("codex", "codex")] {
            assert_eq!(
                runtime_route(&rejected).unwrap_err().code.as_str(),
                "runtime_unavailable"
            );
        }
    }
}
