"""Freeze builtin PII responses exercised by the existing v1 scanner tests.

Run with Python 3.11.6 and pytest, pydantic, regex, and pyyaml installed.
This records synthetic inputs only; regeneration must review changed expected results.
"""

import base64
import functools
import hashlib
import json
import subprocess
import sys
import unicodedata
from pathlib import Path
from typing import Any, Callable

import pytest

ROOT = Path(__file__).resolve().parents[3]
OUTPUT = ROOT / "v2/crates/asc-capability-pii-scan/tests/fixtures/v1.json"
UNICODE_OUTPUT = OUTPUT.parents[2] / "src/python_unicode.rs"


def freeze_character_classes() -> dict[str, str]:
    """Freeze Python's character semantics independently of Rust's Unicode version."""
    if unicodedata.unidata_version != "14.0.0":
        raise RuntimeError("builtin character classes require Unicode 14.0.0")
    lines = [
        "//! Python 3.11.6 / Unicode 14.0.0 character classes for builtin rules.",
        "//! Generated by `tests/v2/fixtures/generate_pii_v1.py`; do not edit by hand.",
        "",
    ]
    hashes = {}
    for name, predicate in [
        ("WORD", lambda c: c == "_" or c.isalnum()),
        ("DECIMAL", str.isdecimal),
    ]:
        ranges: list[tuple[int, int]] = []
        classifications = bytearray()
        for code in range(0x110000):
            if 0xD800 <= code <= 0xDFFF:
                continue
            matched = predicate(chr(code))
            classifications.append(int(matched))
            if matched:
                if ranges and ranges[-1][1] == code - 1:
                    ranges[-1] = (ranges[-1][0], code)
                else:
                    ranges.append((code, code))
        hashes[name.lower()] = hashlib.sha256(classifications).hexdigest()
        lines += [f"pub(super) const {name}_RANGES: &[(char, char)] = &["]
        lines += [
            f"    ('\\u{{{start:x}}}', '\\u{{{end:x}}}')," for start, end in ranges
        ]
        lines += ["];", ""]
    UNICODE_OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    hashes["decimal_values"] = hashlib.sha256(
        bytes(
            unicodedata.decimal(chr(code), 255)
            for code in range(0x110000)
            if not 0xD800 <= code <= 0xDFFF
        )
    ).hexdigest()
    return hashes


class Recorder:
    """Capture calls through v1's test helper without replacing its assertions."""

    def __init__(self) -> None:
        self.records: dict[str, dict[str, Any]] = {}
        self.scan: Callable[..., dict[str, Any]] | None = None

    def pytest_runtest_setup(self, item: Any) -> None:
        module = item.module
        scan = getattr(module, "_scan", None)
        if scan is None or getattr(scan, "_capturing", False):
            return

        @functools.wraps(scan)
        def record(text: str, **kwargs: Any) -> dict[str, Any]:
            result = scan(text, **kwargs)
            # Large-input limits have separate bounded Rust tests. Keeping the
            # golden corpus small makes every expected finding reviewable.
            if len(text.encode("utf-8")) <= 65536:
                expected = json.loads(json.dumps(result))
                expected.pop("elapsed_ms")
                key = json.dumps([text, kwargs], sort_keys=True, ensure_ascii=False)
                self.records[key] = {
                    "text": text,
                    "options": kwargs,
                    "expected": expected,
                }
            return result

        record._capturing = True
        module._scan = record
        self.scan = record


def main() -> int:
    """Run v1's scanner suite, then freeze only its successful baseline."""
    if sys.version_info[:3] != (3, 11, 6):
        raise RuntimeError("fixture generation requires Python 3.11.6")
    sys.path.insert(0, str(ROOT / "agent-sec-cli/src"))
    recorder = Recorder()
    result = pytest.main(
        [
            str(ROOT / "tests/unit-test/pii_checker/test_scanner.py"),
            "-q",
            "--confcutdir=" + str(ROOT / "tests/unit-test/pii_checker"),
        ],
        plugins=[recorder],
    )
    if result:
        return int(result)
    if recorder.scan is None:
        raise RuntimeError("v1 scan helper was not exercised")
    token = "sk-" + "A" * 20
    for text in [
        token + "-=",
        token + "-=中",
        token + "中",
        token + "-BBBB中",
        "中" + token,
        "²" + token,
        "\u0301" + token,
        token + "\u0301",
        "a" + token + "-" + token,
        "sk-" + "A" * 15 + "-中",
        "a" * 70 + "%alice@company.cn",
        "中alice@company.cn",
        "alice@company.cn中",
        "\u0301alice@company.cn\u0301",
        "alice@" + "a" * 70 + ".com",
        "alice@company." + "a" * 70,
        "\U0001e4d0alice@company.cn",
        "alice@company.cn\U0001e4d0",
        "\U0001e4d0" + token,
        token + "\U0001e4d0",
        "\U0001e4d0Bearer abcdefghijklmnop",
        "\U0001e4d0password=abcdefghijklmnop",
        "\U0001e4d0LTAIabcdefghijklmnop",
        "LTAIabcdefghijklmnop\U0001e4d0",
        "\U0001e4f013800138000",
        "13800138000\U0001e4f0",
        "13800138\U0001e4f000",
        "11010519491231002X\U0001e4d0",
        "apİ_key=abcdefghijklmnop",
        "apı_key=abcdefghijklmnop",
        "clİent_secret=abcdefghijklmnop",
        "authorİzatİon=abcdefghijklmnop",
        "authorızatıon=abcdefghijklmnop",
        "gİt+ssh://alice@company.cn/path",
        "Ɤpassword=abcdefghijklmnop",
        "Bearer abcdefghijklmnopİ",
    ]:
        recorder.scan(text, raw_evidence=True)
    headers = [
        '{"alg":"HS256"}',
        r'{"alg":"\ud800"}',
        '{"alg":"HS256","alg":""}',
        '{"alg":"","alg":"HS256"}',
        '{"alg":1e999,"alg":"HS256"}',
        r'{"alg":"\\uD800"}',
        '{"alg":NaN}',
    ]
    payloads = [
        '{"claim":' + value + "}"
        for value in [
            "NaN",
            "Infinity",
            "-Infinity",
            "1e999",
            "1" * 1000,
            r'"\ud800"',
            "[" * 150 + "0" + "]" * 150,
            '"NaN Infinity -Infinity"',
            "-NaN",
            "+Infinity",
            "NaNtrue",
            "Infinity.0",
            "00",
            "[1,]",
            r'"\uXXXX"',
        ]
    ]
    for header, payload, valid in [
        (header, '{"sub":"123"}', index not in {2, 6})
        for index, header in enumerate(headers)
    ] + [(headers[0], payload, index < 8) for index, payload in enumerate(payloads)]:
        segments = [
            base64.urlsafe_b64encode(part.encode()).rstrip(b"=").decode()
            for part in [header, payload]
        ]
        report = recorder.scan(".".join([*segments, "AAAAAAAA"]), raw_evidence=True)
        assert any(f["type"] == "jwt" for f in report["findings"]) == valid
    source = ROOT / "agent-sec-cli/src/agent_sec_cli/pii_checker"
    hashes = {
        str(path.relative_to(source)): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(source.rglob("*.py"))
    }
    commit = subprocess.check_output(
        ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True
    ).strip()
    output = {
        "source_commit": commit,
        "source_sha256": hashes,
        "python": sys.version.split()[0],
        "character_classes_sha256": freeze_character_classes(),
        "cases": list(recorder.records.values()),
    }
    OUTPUT.write_text(
        json.dumps(output, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Frozen {len(recorder.records)} v1 scanner cases in {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
