import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: ['index', 'quickstart', 'building'],
  userGuide: [
    'user-guide/installation',
    {
      type: 'category',
      label: 'User Entry Points',
      items: [{type: 'autogenerated', dirName: 'user-guide/user-entrypoint'}],
    },
    {
      type: 'category',
      label: 'Token Efficiency',
      items: [{type: 'autogenerated', dirName: 'user-guide/token-saving'}],
    },
    {
      type: 'category',
      label: 'Runtime',
      items: [{type: 'autogenerated', dirName: 'user-guide/runtime'}],
    },
    {
      type: 'category',
      label: 'Observability',
      items: [{type: 'autogenerated', dirName: 'user-guide/agent-observability'}],
    },
    {
      type: 'category',
      label: 'Security',
      items: [{type: 'autogenerated', dirName: 'user-guide/agent-security'}],
    },
    'user-guide/troubleshooting',
  ],
  developerGuide: [
    {
      type: 'category',
      label: 'Copilot Shell',
      items: [{type: 'autogenerated', dirName: 'developer-guide/copilot-shell'}],
    },
    {
      type: 'category',
      label: 'Cosh-ng',
      items: [{type: 'autogenerated', dirName: 'developer-guide/cosh-ng'}],
    },
  ],
};

export default sidebars;
