[package]
name = "anolisa-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
nix.workspace = true
dirs.workspace = true
ureq.workspace = true
tempfile.workspace = true
rpmrepo_metadata.workspace = true
quick-xml.workspace = true
sha2.workspace = true
sha1.workspace = true
md-5.workspace = true
url.workspace = true
percent-encoding.workspace = true
liblzma.workspace = true
rustls-native-certs.workspace = true
rust-ini.workspace = true
env_proxy.workspace = true
base64.workspace = true
